### ISSUE TITLE
Installing fails

### ISSUE THREAD

**Issue by rgevaert** [magnusbaeck/logstash-filter-verifier#1]
Hi

I'm trying to get the program working, but can't succeed by following the simple instructions.

```shell
go version go1.5.3 linux/amd64
vagrant@node1:~$ ls
vagrant@node1:~$ mkdir ~/go
vagrant@node1:~$ cd ~/go
vagrant@node1:~/go$ export GOPATH=$(pwd)
vagrant@node1:~/go$ go get github.com/magnusbaeck/logstash-filter-verifier
# github.com/magnusbaeck/logstash-filter-verifier
src/github.com/magnusbaeck/logstash-filter-verifier/logstash-filter-verifier.go:109: undefined: VERSION
````
Uncommenting line 109 lets the compile succeed.

**Comment by magnusbaeck** [comment]
Please run `make` to have version.go generated. Quoting the instructions in README.md:

```
$ mkdir ~/go
$ cd ~/go
$ export GOPATH=$(pwd)
$ go get github.com/magnusbaeck/logstash-filter-verifier
$ cd src/github.com/magnusbaeck/logstash-filter-verifier
$ make
```

**Comment by rgevaert** [comment]
the issue here is that 'go get' fails with the above error.  

(I never used go, so I don't know what is going on, but I suspect the kingpin library changed something that breaks this build)

**Comment by magnusbaeck** [comment]
Oh, sorry. I misread and thought it was the build command that failed. As a workaround you can just clone the git with a regular clone command. Just make sure it ends up in the same location, i.e. $GOPATH/src/github.com/magnusbaeck/logstash-filter-verifier. You'll probably have to run `go get` inside that directory after the manual clone.

**Comment by rgevaert** [comment]
Now I got it to work.  The issue is that "go get github.com/magnusbaeck/logstash-filter-verifier" depends on the version.go file that is not available.  The make command creates it.

A possible update of the README is: "go get -d github.com/magnusbaeck/logstash-filter-verifier".  Then going into the source dir and running makes creates the binary. But I'm sure you already knew that :-)

**Comment by magnusbaeck** [comment]
I've added the `-d` option to the `go get` command in the build instructions. Thanks for the report and the solution! I actually wasn't aware of the `-d option.
