### ISSUE TITLE
Q: Is it possible to see the LFV Logstash output?

### ISSUE THREAD

**Issue by bluebob** [magnusbaeck/logstash-filter-verifier#110]
Platform: Mac, Logstash version: 5.6.15, 7.9.3, 7.11.2, Verifier version: 1.6.3

As the subject line says I'm interested if there's a way to see the Logstash output that the verifier is getting, (like a trace mode I guess). Reason being that I've got a workflow that's producing markedly different output Logstash when the verifier runs Logstash, when compared to running that workflow directly through Logstash.

Not sure if this makes a difference, but I'm using the YAML format for my test cases. And given I've used the Logstash workflow before, (without issue), I'm thinking that perhaps there's something in the current set of test inputs that's causing strange inputs to be fed to Logstash.

**Comment by magnusbaeck** [comment]
Did you try the `--logstash-output` flag?

**Comment by bluebob** [comment]
Thanks, I must have overlooked that one.
