### ISSUE TITLE
Incorrect filter ids result in a timeout on the daemon

### ISSUE THREAD

**Issue by jgough** [magnusbaeck/logstash-filter-verifier#127]
When running in daemon mode, if I have a config file with a nonexistant input filter id, e.g.:

```
input_plugin: "missing_filter_id"
```

Then when I run a test case the daemon waits before outputing:
```
state change: "unknown" because of waitForState timeout
failed to wait for Logstash results: timed out while waiting for state: ready_for_test
```

and the daemon run command exits with
```
logstash-filter-verifier: error: rpc error: code = Unknown desc = destroy of session failed: session teardown failed: state unknown, failed to wait for state: ready_for_test, <nil>
```

It would be very useful to have some error checking here to check that the filter id exists rather than failing in this manner.  Spent a while trying to track this issue down!

**Comment by magnusbaeck** [comment]
Yeah, it's reasonable to have a sanity check that referenced plugins actually exist in the configuration. That shouldn't be too hard to fix.
