### ISSUE TITLE
No config files found

### ISSUE THREAD

**Issue by WhtCmiss** [magnusbaeck/logstash-filter-verifier#167]
Hi, I use basic_pipeline testcase to test, but have some problem.
I start a daemon and test basic_pipeline case, 
The error is 
```./logstash-filter-verifier daemon run --pipeline /root/logstash/basic_pipeline.yml --pipeline-base /root/logstash/main --testcase-dir /root/logstash/basic_pipeline --add-missing-id
logstash-filter-verifier: error: failed to teardown connection: rpc error: code = Unknown desc = destroy of session failed: no valid session found for id "qGdbapZk", root cause: rpc error: code = Unknown desc = timed out while waiting for state: ready_for_test
```
and in the logstash logs, the info is
```
{"level":"INFO","loggerName":"logstash.config.source.local.configpathloader","timeMillis":1638342846765,"thread":"SIGHUP handler","logEvent":{"message":"No config files found in path","path":"/tmp/lfv-267311476/session/qGdbapZk/sut/root/logstash/main/**/*.cfg"}}
```
and after the error, a new instance will be created
```
/tmp/lfv-267311476/session # ls /tmp/lfv-267311476/logstash-instance/
1ck57emS/ PKWZW02i/ Q74GO7V0/
```
The version i use is v2.0.0-beta.2

**Comment by magnusbaeck** [comment]
Where are your configuration files? What's in basic_pipeline.yml?

**Comment by WhtCmiss** [comment]
> 
Hi, The directory is 
/root/logstash
The files in directory is
`
~/logstash # ls
basic_pipeline/  basic_pipeline.yml  logstash-config/  logstash-filter-verifier*  main/  testcase/  testcase1.json  test.cfg  test.yml
`

The info of basic_pipeline.yml is
`
- pipeline.id: main
  path.config: "/root/logstash/main/**/*.cfg"
`
The file in main is
`
~/logstash # ls main
cfg/  main.cfg
`

The file in basic_pipeline is 
`
 ~/logstash # ls basic_pipeline
testcase1.json
`

The start command is 
`
~/logstash # ./logstash-filter-verifier daemon run --pipeline basic_pipeline.yml --pipeline-base main --testcase-dir basic_pipeline --add-missing-id --debug
`
Thank you

**Comment by WhtCmiss** [comment]
> Where are your configuration files? What's in basic_pipeline.yml?

Hi , I download the all testdata directory and test again and the process run success, So,the error mabe teh config file has some problem.
Thank you very much.
But, if the process run error, a new instance will be created, if it's a problem, it must have a check.
