### ISSUE TITLE
For some testcases I needed to isolate the cases to pass the tests. `state change: "unknown" because of waitForState timeout`

### ISSUE THREAD

**Issue by apple-corps** [magnusbaeck/logstash-filter-verifier#170]
I have a set of two test cases testing the same filter. After adding a third test case (with two expected events) and a new input, the test failed. I then isolated this third case. In isolation I was able to pass tests for this third case.

I then attempted to place the third case back along with the two other passing test cases. Regardless of ordering expectations, I could not make the test pass. IIRC in one ordering it would fail expecting the other input first. In the other ordering I'd see `state change: "unknown" because of waitForState timeout` in the logs.

I can try to record some debugging details. But I'm unable to provide my test cases.

Finally I can try to test if changes are made.

**Comment by breml** [comment]
To debug this one, more details are needed.

**Comment by apple-corps** [comment]
can't reproduce. I was able to make the testing work eventually. Closing.
