### ISSUE TITLE
JSON unmarshal does not produce ints

### ISSUE THREAD

**Issue by breml** [magnusbaeck/logstash-filter-verifier#20]
Strictly speaking, [JSON unmarshal](https://golang.org/pkg/encoding/json/#Unmarshal) does not produce ints but only float64. therefore, the following lines of code are not used:

* https://github.com/magnusbaeck/logstash-filter-verifier/blob/master/logstash/fieldset.go#L54-L55
* https://github.com/magnusbaeck/logstash-filter-verifier/blob/master/logstash/fieldset_test.go#L72-L79 (maybe the testcase should be changed to an float without decimal, respectively with a decimal part of 0)

Should we remove this code section?

**Comment by magnusbaeck** [comment]
Yes, why not? Dead code is wasteful and confusing.
