### ISSUE TITLE
Add describe / description on testcases

### ISSUE THREAD

**Issue by disaster37** [magnusbaeck/logstash-filter-verifier#36]
Add the ability to add filed called `describe` or `description` in `testcases` to print it on output.
For exemple, replace 
```
Comparing message 2 of 1_10_beeware_test.json...
``` 
by 
```
Comparing message 2 of 1_10_beeware_test.json ($describe)...
```

**Comment by matejzero** [comment]
I must say I would benefit from this as well. Since JSON doesn't support comments, I sometimes have difficulties figuring out the differences between tests.

In some tests, I only have one or two char that are different and it's hard to spot them or better yet, to know why I test this difference.

**Comment by disaster37** [comment]
Hey, at the moment you can just add filed name "describe" on each testcases. It's work without problem, but this field is not use for stdout the result.

**Comment by magnusbaeck** [comment]
Yes, this was brought up by @breml in #21 and I think it's a great idea.

**Comment by matejzero** [comment]
Oh well, did not think of that:) I guess I'm all set then, but it would make it easier to debug, if it would be printed on the output as well.

**Comment by breml** [comment]
As @magnusbaeck already mentioned, I also thought about this feature. It should not be that hard to implement (maybe I find some time to implement this).
