### ISSUE TITLE
install failed on OSX

### ISSUE THREAD

**Issue by ptillemans** [magnusbaeck/logstash-filter-verifier#53]
Hi,

when running

    $ make install

I get the error 

    install -m 0755 --strip logstash-filter-verifier /usr/local/bin/logstash-filter-verifier
    install: illegal option -- -

In theory this is because the '--strip' long-option is not supported on the mac and only the '-s' short option is available. However this gives the following issue 

    $ install -m 0755 -s logstash-filter-verifier /usr/local/bin/logstash-filter-verifier
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: 
    symbols referenced by indirect symbol table entries that can't be stripped in: /usr/local/bin/logstash-
    filter-verifier
    _malloc
    ___error
    _getnameinfo
    _getaddrinfo
    _free
    ...
    ___stderrp
    install: child process failed: xcrun strip - /usr/local/bin/logstash-filter-verifier

So this does not really help.

The only way out I see is just not to strip the binary when installing to be platform idependent.

**Comment by magnusbaeck** [comment]
Thanks for the report. I'm surprised that `install -s` doesn't work but I'll guess I'll just disable that option for Mac OS X by looking at the `uname -s` output. Unfortunately my only Mac broke down last week so I won't be able to test it.

**Comment by ptillemans** [comment]
Sorry to hear that your Mac broke down... I'll be happy to verify it, if that would help.
