### ISSUE TITLE
Are custom grok pattern files supported ?

### ISSUE THREAD

**Issue by julienvey** [magnusbaeck/logstash-filter-verifier#69]
Hi,

We have several custom patterns in multiple files in a patterns.d directory. 

I haven't found a way to make logstash-filter-verifier aware of them. 
* If I try to add them as config files, the error "Failed to remove the input and output sections" is raised
* If I don't add them, logstash fails (this is expected)

So my question is, how can I use logstash-filter-verifier with custom grok patterns

**Comment by magnusbaeck** [comment]
Are you using a relative path to the pattern file directory? Otherwise I'm not sure I understand why it would fail.

**Comment by julienvey** [comment]
My bad, I was using a wrong config path. Works as expected
