### ISSUE TITLE
enviornment variable

### ISSUE THREAD

**Issue by halleys** [magnusbaeck/logstash-filter-verifier#7]
Hi again, 

My Logstash configuration includes environment variables which needs to be replaced with actual values of the environment variables (e.g. ELK_ROOTDIR). 

```
grok {
    patterns_dir => ["${ELK_ROOTDIR:/}/config/logstash/patterns"]
    match => { "message" => "%{DATESTAMP:recordTime} \[%{INTERFACETYPE:interfaceType}\]  }
  }
```

This is the command I executed to test:

```
bin/logstash-filter-verifier --keep-env=JAVA_HOME --logstash-path=/tools/bin/logstash /config/logstash/tests/test.json /config/logstash/logstash-filter.conf --loglevel=DEBUG
```

This is the outcome of the execution above:

```
2016/10/13 15:27:23 Reading test case file: /config/logstash/tests/test.json (/config/logstash/tests/test.json)
2016/10/13 15:27:23 Prepared configuration file directory /tmp/637939295 with these files: [logstash-filter.conf]
2016/10/13 15:27:23 Starting "/tools/logstash/bin/logstash" with args ["-w" "1" "--debug" "-e" "input { stdin { codec => \"plain\" add_field => { \"path\" => \"/logs/requests.log\" } } } output { file { path => \"/tmp/447820517\" codec => \"json_lines\" } }" "--config" "/tmp/637939295" "--log" "/tmp/079907584"].
2016/10/13 15:27:23 Waiting for child with pid 29288 to terminate.
Testcase failed, continuing with the rest: Expected 11 event(s), got 0 instead.
One or more testcases failed.
```

I tried to run Logstash process with the same arguments I found in the output above:

```
logstash -w 1 --debug -e "input { stdin { codec => \"plain\" add_field => { \"path\" => \"/logs/requests.log\" } } } output { file { path => \"/tmp/447820517\" codec => \"json_lines\" } }" --config /config/logstash/logstash-filter.conf
```

Logstash complains that it can't find 'INTERFACETYPE' pattern which is defined in /config/logstash/patterns.

I don't know this is right approach but after adding '--allow-env' and executing 'make', it works for me.

``` diff
--- a/logstash/process.go
+++ b/logstash/process.go
@@ -73,6 +73,7 @@ func NewProcess(logstashPath, inputCodec string, fields FieldSet, keptEnvVars []
        args := []string{
                "-w", // Make messages arrive in order.
                "1",
+               "--allow-env",
                "--debug",
                "-e",
                fmt.Sprintf(
```

I have tested with 1.1.0, 1.1.1 releases and master branch.

**Comment by magnusbaeck** [comment]
Yes, this is a valid point. LFV never passes `--allow-env` to Logstash which means environment variable references in configuration files don't work for the versions of Logstash that have that option. Logstash 5.0 or 5.1 removed that option and (I think) enabled environment variable support by default so we can't unconditionally pass that option.

However, my plans for supporting Logstash 5 (see #8) include knowing the Logstash version so that e.g. command-line arguments can be adjusted accordingly, and with that in place we could make LFV add `--allow-env` for the Logstash versions that support that feature.

**Comment by breml** [comment]
To provide a flag `--logstash-args` like suggested in https://github.com/magnusbaeck/logstash-filter-verifier/issues/8#issuecomment-283155898 could also help here.
