### ISSUE TITLE
test case on negative scenario

### ISSUE THREAD

**Issue by kercdbh** [magnusbaeck/logstash-filter-verifier#80]
Hi,

is there a way to write a test case for a negative scenario?
Testing for example a filter logic that use [drop](https://www.elastic.co/guide/en/logstash/current/plugins-filters-drop.html) to discard unwanted logs...

I was very naively thinking that setting `expected` to `null` could be the way for a test case to be successful when: "0 message(s) did not match the expectations".

Thanks & regards.

**Comment by magnusbaeck** [comment]
I wouldn't expect setting `expected` to `null` to work, but setting it to an empty list should be fine. Have you tried that?

**Comment by kercdbh** [comment]
`expected: []` did the trick.

Thanks!
