### ISSUE TITLE
Testing cloned events

### ISSUE THREAD

**Issue by jgough** [magnusbaeck/logstash-filter-verifier#81]
If an event is cloned using the `clone` filter then two events are outputted instead of one.

For example this config will output two events - one with slashes replaced with underscores in the message:
```
filter {
  clone { clones => [ "underscores" ] }

  if [type] == "underscores" {
    mutate { gsub => [ "message", "/" "_" ] }
  }
}
```

I can't see any way of testing events that have been cloned.  Is there something that I can do to test this?  If not, can this be a feature request for cloned event support?

**Comment by magnusbaeck** [comment]
Can't you list one event in the input list and two events in the expected list?

**Comment by jgough** [comment]
Could have sworn I tried this, but that does seem to work!  Thanks :-)
