### ISSUE TITLE
Tests Inputs with Codec Options

### ISSUE THREAD

**Issue by jgough** [magnusbaeck/logstash-filter-verifier#82]
Is it possible to specify options for codecs?  I couldn't see that this was possible.

For example, I have the following input plugin:
```
        file {
                path => "/myfolder/*.csv"
                type => "mydata"
                codec => csv {
                        autodetect_column_names => true
                        skip_empty_columns => true
                }
        }
```

Any way to make logstash-filter-verifier use the csv codec with these options?

**Comment by magnusbaeck** [comment]
Yes, as of #77 this is possible. That PR hadn't been included in a release, but I just issued [1.6.1](https://github.com/magnusbaeck/logstash-filter-verifier/releases/tag/1.6.1) that includes it so now you can say

    "codec": "csv { autodetect_column_names => true skip_empty_columns => true }",

in your testcase file to get the behavior you're looking for.
