### ISSUE TITLE
Summary not printed (~ every 10th execution)

### ISSUE THREAD

**Issue by breml** [magnusbaeck/logstash-filter-verifier#92]
I observed, that roughly in every 10th execution, the summary at the end of a logstash-filter-verifier run is not printed. I assume, there is a concurrency issue with the observer.

In https://github.com/magnusbaeck/logstash-filter-verifier/blob/master/logstash-filter-verifier.go#L359 the observer is signaled to print the summary, but there is no waiting for this functionallity to finish so I assume, in some cases, logstash-filter-verifier quits before the summary could be printed to stdout.

**Comment by magnusbaeck** [comment]
Thank you very much! Your analysis was quite correct. I was never able to reproduce it myself but I believe it's fixed with commit 98125d8.

**Comment by breml** [comment]
@magnusbaeck Thanks for the fix. I will have a look at this until the end of the week and provide some feedback.

**Comment by breml** [comment]
@magnusbaeck I tested the new version of logstash-filter-verifier (current master) and I can confirm, that the issue is resolved. Thank you.

Do you mind to release a new version?

**Comment by magnusbaeck** [comment]
Sure, I can probably do that this weekend.

**Comment by magnusbaeck** [comment]
There, [1.6.2](https://github.com/magnusbaeck/logstash-filter-verifier/releases/tag/1.6.2) is available.
