### ISSUE TITLE
Wouldn´t wrap the whole thing in docker environment solve many runtime issues ?

### ISSUE THREAD

**Issue by CyberSeppi** [magnusbaeck/logstash-filter-verifier#98]
Hi there,

just wanted to ask if this wouldn´t be a good thing to have ?

Spin up docker, put the configuration in a locally mounted volume and start testing ?

Thanks and greetings,

Julian

**Comment by magnusbaeck** [comment]
I'm not sure exactly what runtime issues you're thinking of. Are you suggesting we add a dockerfile and publish an image built from it? To make Logstash available from within a container created from that image I guess there are two options:
* Base the LFV image on a Logstash image and publish one image per Logstash version.
* Base the LFV image on a stripped-down Linux (with a JVM) and ask people to mount a directory with the desired Logstash from the host.

Or did you have something else in mind?

**Comment by CyberSeppi** [comment]
Hi,

I guess I just misunderstood how to use this :-(
Thought I would have to need some kind of run time environment around it, to make it work.

My bad, sorry for disturbing :-)

I´ll test it straight away. Have a good weekend and cheers,

Julian

**Comment by magnusbaeck** [comment]
> Thought I would have to need some kind of run time environment around it, to make it work.

Well, an operating system is mandatory :-)

> My bad, sorry for disturbing :-)

No problem.
